name: MCIX CI Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-ci:
    name: Deploy to CI
    runs-on: ubuntu-latest
    environment: ci

    permissions:
      contents: read

    steps:
      - name: Checkout repository         
        uses: actions/checkout@v6

      - name: Verify MCIX runtime
        uses: MettleCI/mcix-system-version@v0


